# Validate with curl --data-binary @.codecov.yml https://codecov.io/validate
coverage:
  precision: 2
  round: down
  range: 90...100
  status:
    # pull-requests only
    patch:
      default:
        # coverage may fall by <2.0% and still be considered "passing"
        threshold: 2.0%

comment:
  layout: "header, diff, changes"
