
dist: xenial   # required for Python >= 3.7
language: python
sudo: false

cache:
  directories:
  - "$HOME/.cache/pip"

python:
- nightly
- pypy3

env:

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry python setup.py sdist bdist_wheel
  - travis_retry pip install -e .[test]

script:
  - pytest --cov=anonlink -W ignore::DeprecationWarning
  - codecov

jobs:
  fast_finish: true
  allow_failures:
    - python: "nightly"
    - python: "pypy3"
    - name: "Extended Size 100K"
  include:
    # No matrix support in Stages
    # Stages with the same name get run in parallel. Jobs within a stage can also be named.
    - stage: test
      name: "Extended Size 10K"
      python: "3.7"
      env:
        - INCLUDE_10K=1
    - stage: test
      name: "Extended Size 100K"
      python: "3.7"
      env:
        - INCLUDE_100K=1
