
dist: xenial   # required for Python >= 3.7
language: python
sudo: false

cache:
  directories:
  - "$HOME/.cache/pip"

python:
- 3.6
- 3.7
- 3.8-dev
- nightly
- pypy3

env:

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry python setup.py sdist bdist_wheel
  - travis_retry pip install -e .[test]

script:
  - pytest --cov=anonlink -W ignore::DeprecationWarning
  - codecov

jobs:
  fast_finish: true
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"
    - python: "pypy3"
    - name: "Extended 100K"
  include:
    # No matrix support in Stages
    # Stages with the same name get run in parallel. Jobs within a stage can also be named.
    - stage: test
      name: "Extended Size 10K"
      python: "3.7"
      env:
        - INCLUDE_10K=1
    - stage: test
      name: "Extended Size 100K"
      python: "3.7"
      env:
        - INCLUDE_100K=1
    - stage: test
      name: "Typecheck"
      python: "3.7"
      before_install:
        - travis_retry pip install -U mypy
      script:
        - mypy anonlink --ignore-missing-imports
    - stage: Build wheels
      sudo: required
      if: tag IS present
      python: "3.6"
      services:
      - docker
      env:
        - secure: "mludl5NTGnCyiMeJ4J7Y2juy+od3vaf3zWpD7mPKij0ezKJ+6Pc3WfBtWSlonQIM6I7jLLStFi15/vGKDP1DprkFLzJ9VNtwzCUNYK2Euswmq6t9WHWK1OR/6P7XKAiJ3TpRF2CuleG++SjIGWc9pUHj+ch8ALcZztZ9MeSR+BW1zim7WpA9lAjLwbnkYqje/aRtOJnSuqDIPwyJBsJlra17/9srBpDYQ8hFULl7EUd9SB2im7ZfCGS2ToqTuU8gYzaikakHXbQ076oliTauCJxSKvrsvXi7Tr4So32lvaJwmSPw/ci+5pgUxFIoIa26EsljU506A1+Ucs4LW8W/5iMg3pDPP+AhJVVaq5Kb2wMZ+5ITzH/1O200zcP7RHVCo6y/1NA96vFAP1rsQFg7ucFGa2orUC+Xd2dWz2TPA32VdvBKUlcPkhD+RPh381/l4MXmXgadexPWDwwcon67zfbFBGyBbDmjEeRwD1pYOYgqoUx1AFxw/rkfwZ2wlXPXxLa8o35YifKdOxbL0RHHvvR5nBhJkgWD5WZNBmTdubzLbEhJbdM+LcdAJ3cQTGgu4+O/TfTRF+woNB+/LQvJ2KseCIBolu0nX40uRpriAl1rtil+rCUyOUz82I8NFuOTDjfIGNV2Ey5dAVK9+ZbXbVusUNl7xjc827g85hThJq8="
      install: docker pull quay.io/pypa/manylinux1_x86_64
      script:
      - docker run --rm --e TWINE_PASSWORD -v `pwd`:/io quay.io/pypa/manylinux1_x86_64 /io/travis/build-wheels.sh
      - ls wheelhouse/
