
dist: xenial   # required for Python >= 3.7
language: python
sudo: false

cache:
  directories:
  - "$HOME/.cache/pip"

python:
- 3.6
- 3.7
- 3.8-dev
- nightly
- pypy3

env:

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry python setup.py sdist bdist_wheel
  - travis_retry pip install -e .[test]

script:
  - pytest --cov=anonlink -W ignore::DeprecationWarning
  - codecov

jobs:
  fast_finish: true
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"
    - python: "pypy3"
    - name: "Extended 100K"
  include:
    # No matrix support in Stages
    # Stages with the same name get run in parallel. Jobs within a stage can also be named.
    - stage: test
      name: "Extended Size 10K"
      python: "3.7"
      env:
        - INCLUDE_10K=1
    - stage: test
      name: "Extended Size 100K"
      python: "3.7"
      env:
        - INCLUDE_100K=1
    - stage: test
      name: "Typecheck"
      python: "3.7"
      before_install:
        - travis_retry pip install -U mypy
      script:
        - mypy anonlink --ignore-missing-imports
    - stage: Build wheels
      sudo: required
      if: tag IS present
      python: "3.6"
      services:
      - docker
      env:
        - PLAT=manylinux1_x86_64
        - TWINE_USERNAME=confidentialcomputing
      install:
        - docker pull quay.io/pypa/manylinux1_x86_64
        - travis_retry pip install -U twine
      script:
      - docker run --rm -e PLAT=$PLAT -v `pwd`:/io quay.io/pypa/manylinux1_x86_64 /io/travis/build-wheels.sh
      - ls wheelhouse/
      - python -m twine upload wheelhouse/*.whl
