
dist: xenial   # required for Python >= 3.7
language: python
sudo: false

cache:
  directories:
  - "$HOME/.cache/pip"

python:
- 3.6
- 3.7
- 3.8-dev
- nightly
- pypy3

env:

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry python setup.py sdist bdist_wheel
  - travis_retry pip install -e .[test]

script:
  - pytest --cov=anonlink -W ignore::DeprecationWarning
  - codecov

jobs:
  fast_finish: true
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"
    - python: "pypy3"
    - name: "Extended 100K"
  include:
    # No matrix support in Stages
    # Stages with the same name get run in parallel. Jobs within a stage can also be named.
    - stage: test
      name: "Extended Size 10K"
      python: "3.7"
      env:
        - INCLUDE_10K=1
    - stage: test
      name: "Extended Size 100K"
      python: "3.7"
      env:
        - INCLUDE_100K=1
    - stage: test
      name: "Typecheck"
      python: "3.7"
      before_install:
        - travis_retry pip install -U mypy
      script:
        - mypy anonlink --ignore-missing-imports
    - stage: Build wheels
      sudo: required
      python: "3.6"
      services:
      - docker
      env:
        - PLAT=manylinux1_x86_64
      install: docker pull quay.io/pypa/manylinux1_x86_64
      script:
      - docker run --rm -e PLAT=$PLAT -v `pwd`:/io quay.io/pypa/manylinux1_x86_64 /io/travis/build-wheels.sh
      - ls wheelhouse/
      deploy:
        provider: pypi
        user: confidentialcomputing
        password:
          secure: lXO+O26PFznLnhNTK/HaQrXrV4j7vlkKGdfG/mPMb6i1HXI14WQa8gsQwCWAc845nk1J8IYmCzLev9wOX15ZYYSnrBYCSLzQGTvX5l0EuAEQmiu8AMN2ZyVu+vDnaZSAsDdGYBjbrnz+PCyEwu0YvcQ1xbtPa2b8IvhVx9Oi5XCErxLAjxVdxSNDfe3riexbOE27di++wjwremp+hGezQMu4mcQkDH84WAHh1RfCfRuAZ6zsXnv+BSRUnmEedIL4wkupAY79OvcavPCHQBf1nbQ3CqcBhXehEM4Q7ZTWFe8kb5wPfpHq1mFsBbCY6rVbfvo5AgJFPfkXi+3NBNPIXdAk7/sTfjfBSZfMbgI9Cd4XmbkG5YYLTtBemH07/HBK+jnbNEc2Iw5LQyuvmlQl6nmWEjI4tXo8mNBIurMHr3junashIxLwG+NDs+BO/wz6GA7xWgl0CMxbCbo73Bq5DNti5toClhQc2mvSf14GMkuLkTU0UBD6F6flF81sDZsTX9nUmtAzGb60ccLsCuo5LPh1P05wjUpdeRGtwB5LOGQWLwSsq8blTpsYDWfcPreAIWzwqAjPpyzDvs+02SBVErt/0zxBN0zf0ybC1XLI8N91yViGSBJvGIJZ8tNpaXmPKflHZ+Z/gHc4+86LW+dqsrfXL+jOSCDwXh0JBypHIxo=
        on:
          tags: true
        skip_cleanup: true
        file:
        - wheelhouse/anonlink-*.whl
