language: python

python:
  - '3.6'
  - '3.7-dev'
  - 'nightly'
  - 'pypy3'

env:
  - INCLUDE_10K=

matrix:
  allow_failures:
    - python: '3.7-dev'
    - python: 'nightly'
    - python: 'pypy3'
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - travis_retry pip install pytest pytest-cov
  - travis_retry pip install -r requirements.txt
  - travis_retry python setup.py sdist bdist_wheel
  - travis_retry pip install -e .
  - docker pull $DOCKER_IMAGE

script:
  - pytest --cov=anonlink
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/