language: python
sudo: false

python:
  - '3.6'
  - '3.7-dev'
  - 'nightly'
  - 'pypy3'

env:
  - INCLUDE_10K=

matrix:
  allow_failures:
    - python: '3.7-dev'
    - python: 'nightly'
    - python: 'pypy3'

jobs:
  include:
    - stage: Build wheels
      sudo: required
      python: '3.6'
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
      install: docker pull $DOCKER_IMAGE
      script:
        - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/travis/build-wheels.sh
        - ls wheelhouse/

install:
  - travis_retry pip install pytest pytest-cov
  - if [ -n "$USE_ASV" ]; then pip install asv; fi
  - travis_retry pip install -r requirements.txt
  - travis_retry python setup.py sdist bdist_wheel
  - travis_retry pip install -e .

script:
  - pytest --cov=anonlink
