name: Build and upload to PyPI

on:
  release:
    types: [ published ]
  push:
    branches:
      - 'main'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        # to supply options, put them in 'env', like:
        env:
         CIBW_SKIP: '*-win32 *i686'

      - uses: actions/upload-artifact@v3
        with:
          name: binary-wheels
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          name: binary-wheels
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest

    # upload to PyPI on every release
    if: github.event.type == 'ReleaseEvent'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: binary-wheels
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
